#pragma once

#include <QString>
#include <QVariant>
#include <QVector>

struct CameraCommandOption
{
    QString label;            ///< Human readable label shown in the UI
    QString data;             ///< Data payload associated with the option
    QString description;      ///< Optional tooltip/description
};

struct CameraCommandDefinition
{
    QString key;              ///< Unique identifier within the application
    QString category;         ///< Group heading shown in the UI
    QString label;            ///< Button label
    QString description;      ///< Optional longer description

    QString header;           ///< Frame header (e.g., "#tp", "#TP", "#tP")
    QChar destination;        ///< Destination address (M, D, G, ...)
    QChar serialSource;       ///< Source address when using UART (default 'U')
    QChar udpSource;          ///< Source address when using UDP (default 'P')
    QChar control;            ///< Control byte ('w' or 'r')
    QString identifier;       ///< Three-character identifier

    QString defaultData;      ///< Default data field (ASCII unless dataIsHexPayload)
    bool dataEditable = false;///< Does the UI expose a text field for custom data
    QString dataHint;         ///< Hint/placeholder describing expected data format
    QVector<CameraCommandOption> options; ///< Optional predefined data options

    int lengthFieldWidth = 1; ///< Number of ASCII hex chars used for length (1 or 2)
    bool dataIsHexPayload = false; ///< Interpret data as hexadecimal byte stream
    bool allowEmptyData = true;    ///< Whether empty data field is valid
    bool autoGenerateData = false; ///< Controller generates data dynamically
};

QVariantMap cameraCommandOptionToVariant(const CameraCommandOption& option);
QVariantMap cameraCommandDefinitionToVariant(const CameraCommandDefinition& definition);
