#include "CameraCommandDefinition.h"

#include <QVariantMap>
#include <QVariantList>

QVariantMap cameraCommandOptionToVariant(const CameraCommandOption& option)
{
    QVariantMap map;
    map.insert(QStringLiteral("label"), option.label);
    map.insert(QStringLiteral("data"), option.data);
    if (!option.description.isEmpty()) {
        map.insert(QStringLiteral("description"), option.description);
    }
    return map;
}

QVariantMap cameraCommandDefinitionToVariant(const CameraCommandDefinition& definition)
{
    QVariantMap map;
    map.insert(QStringLiteral("key"), definition.key);
    map.insert(QStringLiteral("category"), definition.category);
    map.insert(QStringLiteral("label"), definition.label);
    map.insert(QStringLiteral("description"), definition.description);
    map.insert(QStringLiteral("header"), definition.header);
    map.insert(QStringLiteral("destination"), QString(definition.destination));
    map.insert(QStringLiteral("serialSource"), QString(definition.serialSource));
    map.insert(QStringLiteral("udpSource"), QString(definition.udpSource));
    map.insert(QStringLiteral("control"), QString(definition.control));
    map.insert(QStringLiteral("identifier"), definition.identifier);
    map.insert(QStringLiteral("defaultData"), definition.defaultData);
    map.insert(QStringLiteral("dataEditable"), definition.dataEditable);
    map.insert(QStringLiteral("dataHint"), definition.dataHint);
    map.insert(QStringLiteral("lengthFieldWidth"), definition.lengthFieldWidth);
    map.insert(QStringLiteral("dataIsHexPayload"), definition.dataIsHexPayload);
    map.insert(QStringLiteral("allowEmptyData"), definition.allowEmptyData);
    map.insert(QStringLiteral("autoGenerateData"), definition.autoGenerateData);

    QVariantList optionList;
    optionList.reserve(definition.options.size());
    for (const CameraCommandOption& option : definition.options) {
        optionList.append(cameraCommandOptionToVariant(option));
    }
    map.insert(QStringLiteral("options"), optionList);
    map.insert(QStringLiteral("hasOptions"), !optionList.isEmpty());
    return map;
}
